name: Publish Package to PyPI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish_to_pypi:
    name: Push Package to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install wheel setuptools

      - name: Install Doreah (imported on build)
        run: pip install doreah

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
